<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "srevents"
 *
 * Auto generated by Extension Builder 2014-04-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SR Events',
	'description' => 'Just another event extension.',
	'category' => 'plugin',
	'author' => 'Sebastian Reese',
	'author_email' => 'sebastian.reese@aoe.com',
	'author_company' => 'AOE GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>